<div class="item_container">
<!--
	<a href="/reference/api/dhcp"><div style="reference_index">DHCP</div></a>
	<a href="/reference/api/dns"><div style="reference_index">DNS</div></a>
	<a href="/reference/api/firewall"><div style="reference_index">Firewall</div></a>
	<a href="/reference/api/ip"><div style="reference_index">IP</div></a>
	<a href="/reference/api/management"><div style="reference_index">Management</div></a>
	<a href="/reference/api/network"><div style="reference_index">Network</div></a>
	<a href="/reference/api/systems"><div style="reference_index">Systems</div></a>
	<a href="/reference/api/all"><div style="reference_index">All</div></a>
	<a href="/reference/api/none"><div style="reference_index">None</div></a>
-->
	This is a reference for all of the IMPULSE API functions. These functions are what drive all clients
	(including this one!) and are the only supported way of interacting with the database.
	<p>
	Functions are organized by the relative schema that they affect. Note that not all functions may 
	end up in the expected container. The documentation is autogenerated once in a while directly from 
	the functions, so they don't always end up in the right place.
</div>
