psql -f Jumpstart.sql
psql -f Setup.sql impulse
psql -f api_dhcp.sql impulse
psql -f api_dns.sql impulse
psql -f api_firewall.sql impulse
psql -f api_ip.sql impulse
psql -f api_management.sql impulse
psql -f api_network.sql impulse
psql -f api_systems.sql impulse
psql -f Tables.sql impulse
psql -f Constraints.sql impulse
psql -f triggers_dhcp.sql impulse
psql -f triggers_dns.sql impulse
psql -f triggers_firewall.sql impulse
psql -f triggers_ip.sql impulse
psql -f triggers_management.sql impulse
psql -f triggers_network.sql impulse
psql -f triggers_systems.sql impulse
psql -f triggers.sql impulse
psql -f Views.sql impulse
psql -f Base.sql impulse
psql -f Privileges.sql impulse