DROP FUNCTION api.change_username(text, text);
DROP FUNCTION api.check_dns_hostname(text, text);
DROP FUNCTION api.clean_log();
DROP FUNCTION api.clear_expired_systems();
DROP FUNCTION api.create_address_range(inet, inet, cidr);
DROP FUNCTION api.create_availability_zone(text, text, text);
DROP FUNCTION api.create_datacenter(text, text);
DROP FUNCTION api.create_dhcp_class(text, text);
DROP FUNCTION api.create_dhcp_class_option(text, text, text);
DROP FUNCTION api.create_dhcp_global_option(text, text);
DROP FUNCTION api.create_dhcp_range_option(text, text, text);
DROP FUNCTION api.create_dhcp_subnet_option(cidr, text, text);
DROP FUNCTION api.create_dns_address(inet, text, text, integer, text, boolean, text);
DROP FUNCTION api.create_dns_cname(text, text, text, integer, text);
DROP FUNCTION api.create_dns_key(text, text, text, text);
DROP FUNCTION api.create_dns_mailserver(text, text, integer, integer, text);
DROP FUNCTION api.create_dns_ns(text, text, inet, integer);
DROP FUNCTION api.create_dns_soa(text, integer, text, text, text, integer, integer, integer, integer);
DROP FUNCTION api.create_dns_srv(text, text, text, integer, integer, integer, integer, text);
DROP FUNCTION api.create_dns_txt(text, text, text, integer, text);
DROP FUNCTION api.create_dns_zone(text, text, boolean, boolean, text, text, boolean);
DROP FUNCTION api.create_dns_zone_a(text, inet, integer);
DROP FUNCTION api.create_dns_zone_txt(text, text, text, integer);
DROP FUNCTION api.create_group(text, text, text, interval);
DROP FUNCTION api.create_group_member(text, text, text);
DROP FUNCTION api.create_interface(text, macaddr, text, text);
DROP FUNCTION api.create_interface_address(macaddr, inet, text, text, boolean, text, date);
DROP FUNCTION api.create_ip_range(text, inet, inet, cidr, character varying, text, text, text, text);
DROP FUNCTION api.create_ip_subnet(cidr, text, text, boolean, boolean, text, text, text, integer);
DROP FUNCTION api.create_network_snmp(text, inet, text, text);
DROP FUNCTION api.create_platform(text, text, text, text, integer);
DROP FUNCTION api.create_site_configuration(text, text);
DROP FUNCTION api.create_system(text, text, text, text, text, text, text, text, text);
DROP FUNCTION api.create_system_quick(text, text, text, macaddr, inet, text, text);
DROP FUNCTION api.create_vlan(text, integer, text, text);
DROP FUNCTION api.deinitialize();
DROP FUNCTION api.dns_clean_zone_a(text);
DROP FUNCTION api.dns_clean_zone_ptr(text);
DROP FUNCTION api.dns_forward_lookup(text);
DROP FUNCTION api.dns_resolve(text, text, integer);
DROP FUNCTION api.dns_zone_audit(text);
DROP FUNCTION api.exec(text);
DROP FUNCTION api.generate_dhcpd_config();
DROP FUNCTION api.get_address_from_range(text);
DROP FUNCTION api.get_address_range(inet);
DROP FUNCTION api.get_availability_zones();
DROP FUNCTION api.get_current_user();
DROP FUNCTION api.get_current_user_groups();
DROP FUNCTION api.get_current_user_level();
DROP FUNCTION api.get_datacenters();
DROP FUNCTION api.get_default_renew_date(text);
DROP FUNCTION api.get_dhcp_class(text);
DROP FUNCTION api.get_dhcp_class_options(text);
DROP FUNCTION api.get_dhcp_classes();
DROP FUNCTION api.get_dhcp_config_types(integer);
DROP FUNCTION api.get_dhcp_global_options();
DROP FUNCTION api.get_dhcp_range_options(text);
DROP FUNCTION api.get_dhcp_subnet_options(cidr);
DROP FUNCTION api.get_dhcpd_class_options(text);
DROP FUNCTION api.get_dhcpd_classes();
DROP FUNCTION api.get_dhcpd_config();
DROP FUNCTION api.get_dhcpd_dns_keys();
DROP FUNCTION api.get_dhcpd_dynamic_hosts();
DROP FUNCTION api.get_dhcpd_forward_zones();
DROP FUNCTION api.get_dhcpd_global_options();
DROP FUNCTION api.get_dhcpd_range_options(text);
DROP FUNCTION api.get_dhcpd_reverse_zones();
DROP FUNCTION api.get_dhcpd_static_hosts();
DROP FUNCTION api.get_dhcpd_subnet_options(cidr);
DROP FUNCTION api.get_dhcpd_subnet_ranges(cidr);
DROP FUNCTION api.get_dhcpd_subnets();
DROP FUNCTION api.get_dns_a(inet, text);
DROP FUNCTION api.get_dns_cname(inet);
DROP FUNCTION api.get_dns_key(text);
DROP FUNCTION api.get_dns_keys(text);
DROP FUNCTION api.get_dns_mx(inet);
DROP FUNCTION api.get_dns_ns(text);
DROP FUNCTION api.get_dns_soa(text);
DROP FUNCTION api.get_dns_srv(inet);
DROP FUNCTION api.get_dns_txt(inet);
DROP FUNCTION api.get_dns_zone(text);
DROP FUNCTION api.get_dns_zone_a(text);
DROP FUNCTION api.get_dns_zone_txt(text);
DROP FUNCTION api.get_dns_zones(text);
DROP FUNCTION api.get_function_counts(text);
DROP FUNCTION api.get_group_admins(text);
DROP FUNCTION api.get_group_members(text);
DROP FUNCTION api.get_groups();
DROP FUNCTION api.get_interface_address_owner(inet);
DROP FUNCTION api.get_interface_address_system(inet);
DROP FUNCTION api.get_interface_owner(macaddr);
DROP FUNCTION api.get_interface_switchports(macaddr);
DROP FUNCTION api.get_interface_system(macaddr);
DROP FUNCTION api.get_ip_range_total(text);
DROP FUNCTION api.get_ip_range_uses();
DROP FUNCTION api.get_ip_ranges();
DROP FUNCTION api.get_ip_subnets(text);
DROP FUNCTION api.get_ldap_user_level(text);
DROP FUNCTION api.get_local_user_level(text);
DROP FUNCTION api.get_network_snmp(text);
DROP FUNCTION api.get_network_switchport(text, integer);
DROP FUNCTION api.get_network_switchports(text);
DROP FUNCTION api.get_operating_systems();
DROP FUNCTION api.get_os_distribution();
DROP FUNCTION api.get_os_family_distribution();
DROP FUNCTION api.get_owned_interface_addresses(text);
DROP FUNCTION api.get_platforms();
DROP FUNCTION api.get_range_addresses(inet, inet);
DROP FUNCTION api.get_range_utilization(text);
DROP FUNCTION api.get_record_types();
DROP FUNCTION api.get_reverse_domain(inet);
DROP FUNCTION api.get_search_data();
DROP FUNCTION api.get_site_configuration(text);
DROP FUNCTION api.get_site_configuration_all();
DROP FUNCTION api.get_subnet_addresses(cidr);
DROP FUNCTION api.get_subnet_utilization(cidr);
DROP FUNCTION api.get_switchview_bridgeportid(inet, text, integer);
DROP FUNCTION api.get_switchview_cam(inet, text, integer);
DROP FUNCTION api.get_switchview_device_cam(text);
DROP FUNCTION api.get_switchview_device_switchports(text);
DROP FUNCTION api.get_switchview_neighbors(inet, text);
DROP FUNCTION api.get_switchview_port_adminstatus(inet, text);
DROP FUNCTION api.get_switchview_port_descriptions(inet, text);
DROP FUNCTION api.get_switchview_port_names(inet, text);
DROP FUNCTION api.get_switchview_port_operstatus(inet, text);
DROP FUNCTION api.get_switchview_portindex(inet, text, integer);
DROP FUNCTION api.get_system(text);
DROP FUNCTION api.get_system_architectures();
DROP FUNCTION api.get_system_cam(text);
DROP FUNCTION api.get_system_interface_address(inet);
DROP FUNCTION api.get_system_interface_addresses(macaddr);
DROP FUNCTION api.get_system_interface_data(macaddr);
DROP FUNCTION api.get_system_interfaces(text);
DROP FUNCTION api.get_system_owner(text);
DROP FUNCTION api.get_system_permissions(text);
DROP FUNCTION api.get_system_primary_address(text);
DROP FUNCTION api.get_system_switchports(text);
DROP FUNCTION api.get_system_types();
DROP FUNCTION api.get_systems(text);
DROP FUNCTION api.get_vlans(text);
DROP FUNCTION api.initialize(text);
DROP FUNCTION api.ip_arp(inet);
DROP FUNCTION api.ip_in_subnet(inet, cidr);
DROP FUNCTION api.ip_is_dynamic(inet);
DROP FUNCTION api.modify_availability_zone(text, text, text, text);
DROP FUNCTION api.modify_datacenter(text, text, text);
DROP FUNCTION api.modify_dhcp_class(text, text, text);
DROP FUNCTION api.modify_dhcp_class_option(text, text, text, text, text);
DROP FUNCTION api.modify_dhcp_global_option(text, text, text, text);
DROP FUNCTION api.modify_dhcp_range_option(text, text, text, text, text);
DROP FUNCTION api.modify_dhcp_subnet_option(cidr, text, text, text, text);
DROP FUNCTION api.modify_dns_address(inet, text, text, text);
DROP FUNCTION api.modify_dns_cname(text, text, text, text);
DROP FUNCTION api.modify_dns_key(text, text, text);
DROP FUNCTION api.modify_dns_mailserver(text, text, text, text);
DROP FUNCTION api.modify_dns_ns(text, text, text, text);
DROP FUNCTION api.modify_dns_soa(text, text, text);
DROP FUNCTION api.modify_dns_srv(text, text, integer, integer, integer, text, text);
DROP FUNCTION api.modify_dns_txt(text, text, text, text, text);
DROP FUNCTION api.modify_dns_zone(text, text, text);
DROP FUNCTION api.modify_dns_zone_a(text, inet, text, text);
DROP FUNCTION api.modify_dns_zone_txt(text, text, text, text, text);
DROP FUNCTION api.modify_group(text, text, text);
DROP FUNCTION api.modify_group_member(text, text, text, text);
DROP FUNCTION api.modify_interface(macaddr, text, text);
DROP FUNCTION api.modify_interface_address(inet, text, text);
DROP FUNCTION api.modify_ip_range(text, text, text);
DROP FUNCTION api.modify_ip_subnet(cidr, text, text);
DROP FUNCTION api.modify_network_snmp(text, text, text);
DROP FUNCTION api.modify_network_switchport(text, text, text, text);
DROP FUNCTION api.modify_network_switchport_admin_state(inet, text, text, boolean);
DROP FUNCTION api.modify_network_switchport_description(inet, text, text, text);
DROP FUNCTION api.modify_platform(text, text, text);
DROP FUNCTION api.modify_site_configuration(text, text);
DROP FUNCTION api.modify_switchport_admin_state(text, text, boolean);
DROP FUNCTION api.modify_system(text, text, text);
DROP FUNCTION api.modify_system_switchview(text, text, text);
DROP FUNCTION api.modify_vlan(text, integer, text, text);
DROP FUNCTION api.notify_expiring_addresses();
DROP FUNCTION api.notify_expiring_systems();
DROP FUNCTION api.nslookup(inet);
DROP FUNCTION api.nsupdate(text, text, text, inet, text, text);
DROP FUNCTION api.query_address_reverse(inet);
DROP FUNCTION api.query_axfr(text, text);
DROP FUNCTION api.query_zone_serial(text);
DROP FUNCTION api.reload_cam(text);
DROP FUNCTION api.reload_network_switchports(text);
DROP FUNCTION api.remove_availability_zone(text, text);
DROP FUNCTION api.remove_datacenter(text);
DROP FUNCTION api.remove_dhcp_class(text);
DROP FUNCTION api.remove_dhcp_class_option(text, text, text);
DROP FUNCTION api.remove_dhcp_global_option(text, text);
DROP FUNCTION api.remove_dhcp_range_option(text, text, text);
DROP FUNCTION api.remove_dhcp_subnet_option(cidr, text, text);
DROP FUNCTION api.remove_dns_address(inet, text);
DROP FUNCTION api.remove_dns_cname(text, text);
DROP FUNCTION api.remove_dns_key(text);
DROP FUNCTION api.remove_dns_mailserver(text, integer);
DROP FUNCTION api.remove_dns_ns(text, text);
DROP FUNCTION api.remove_dns_soa(text);
DROP FUNCTION api.remove_dns_srv(text, text, integer, integer, integer);
DROP FUNCTION api.remove_dns_txt(text, text, text);
DROP FUNCTION api.remove_dns_zone(text);
DROP FUNCTION api.remove_dns_zone_a(text, inet);
DROP FUNCTION api.remove_dns_zone_txt(text, text, text);
DROP FUNCTION api.remove_group(text);
DROP FUNCTION api.remove_group_member(text, text);
DROP FUNCTION api.remove_interface(macaddr);
DROP FUNCTION api.remove_interface_address(inet);
DROP FUNCTION api.remove_ip_range(text);
DROP FUNCTION api.remove_ip_subnet(cidr);
DROP FUNCTION api.remove_network_snmp(text);
DROP FUNCTION api.remove_platform(text);
DROP FUNCTION api.remove_site_configuration(text);
DROP FUNCTION api.remove_system(text);
DROP FUNCTION api.remove_users_systems(text);
DROP FUNCTION api.remove_vlan(text, integer);
DROP FUNCTION api.renew_interface_address(inet);
DROP FUNCTION api.resolve(text);
DROP FUNCTION api.send_renewal_email(text, text, text);
DROP FUNCTION api.send_renewal_email(text, inet, text, text);
DROP FUNCTION api.send_renewal_email(text, inet, text, text, text);
DROP FUNCTION api.validate_domain(text, text);
DROP FUNCTION api.validate_name(text);
DROP FUNCTION api.validate_nospecial(text);
DROP FUNCTION api.validate_soa_contact(text);
DROP FUNCTION api.validate_srv(text);
