DROP DATABASE IF EXISTS STARRSDBNAME;

CREATE DATABASE STARRSDBNAME WITH OWNER STARRSADMINUSER;
COMMENT ON DATABASE "STARRSDBNAME" IS 'STARRS network management application';

DROP SCHEMA IF EXISTS "public";

DO $$ BEGIN IF (SELECT COUNT("rolname") FROM "pg_roles" WHERE "rolname" = 'STARRSADMINUSER') != 1 THEN CREATE USER "STARRSADMINUSER" WITH PASSWORD 'STARRSADMINPASSWORD'; END IF; END $$;
DO $$ BEGIN IF (SELECT COUNT("rolname") FROM "pg_roles" WHERE "rolname" = 'STARRSCLIENTUSER') != 1 THEN CREATE USER "STARRSCLIENTUSER" WITH PASSWORD 'STARRSCLIENTPASSWORD'; END IF; END $$;
