/* Privileges */

/* Schemas
	Allow access to the schemas
*/
GRANT USAGE ON SCHEMA "api" TO "STARRSCLIENTUSER";
GRANT USAGE ON SCHEMA "dhcp" TO "STARRSCLIENTUSER";
GRANT USAGE ON SCHEMA "dns" TO "STARRSCLIENTUSER";
GRANT USAGE ON SCHEMA "ip" TO "STARRSCLIENTUSER";
GRANT USAGE ON SCHEMA "management" TO "STARRSCLIENTUSER";
GRANT USAGE ON SCHEMA "network" TO "STARRSCLIENTUSER";
GRANT USAGE ON SCHEMA "systems" TO "STARRSCLIENTUSER";
GRANT USAGE ON SCHEMA "libvirt" TO "STARRSCLIENTUSER";

/* System Data
	Clients should never be able to modify these. They are for administrators only (superuser)
*/
GRANT SELECT ON "ip"."range_uses" TO "STARRSCLIENTUSER";
GRANT SELECT ON "systems"."device_types" TO "STARRSCLIENTUSER";
GRANT SELECT ON "systems"."os_family" TO "STARRSCLIENTUSER";
GRANT SELECT ON "dhcp"."config_types" TO "STARRSCLIENTUSER";
GRANT SELECT ON "systems"."os" TO "STARRSCLIENTUSER";
GRANT SELECT ON "dns"."types" TO "STARRSCLIENTUSER";
GRANT SELECT ON "systems"."architectures" TO "STARRSCLIENTUSER";

/* User Data
	This is all the stuff that clients can (depending on user permission level) modify
*/
GRANT SELECT,INSERT,UPDATE,DELETE ON "dhcp"."class_options" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "ip"."subnets" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "ip"."ranges" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "dns"."ns" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "systems"."interface_addresses" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "dhcp"."classes" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "systems"."systems" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "dhcp"."subnet_options" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "dns"."mx" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "dns"."zones" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "dns"."keys" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "ip"."addresses" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "dns"."txt" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "dns"."a" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "systems"."interfaces" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "management"."configuration" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "dhcp"."global_options" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "dhcp"."range_options" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "dns"."soa" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "dns"."srv" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "dns"."cname" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "dns"."zone_txt" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "dns"."zone_a" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "network"."snmp" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "management"."groups" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "management"."group_members" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "systems"."datacenters" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "systems"."availability_zones" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "systems"."platforms" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "network"."vlans" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "network"."cam_cache" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "libvirt"."hosts" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT,UPDATE,DELETE ON "ip"."range_groups" TO "STARRSCLIENTUSER";

/* Special Data
	Read or Write only, not both
*/
GRANT SELECT,INSERT ON "management"."log_master" TO "STARRSCLIENTUSER";
GRANT SELECT,INSERT ON "management"."output" TO "STARRSCLIENTUSER";

GRANT USAGE,SELECT ON SEQUENCE "management"."output_id_seq" TO "STARRSCLIENTUSER";
